Cloud testapp
Otus-DevOps-2023-09/GideonRavenor1_infra pull request #3
Opened 2023-11-11 13:24 UTC by GideonRavenor1

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Создана ВМ через CLI
- Установлены Ruby, MongoDB, App - Reddit
- Написаны скрипты для установки всех компонентов
- Написан startup config и команда для CLI, что позволяет одной командой запустить ВМ с необходимыми компонентами

## Как запустить проект:
 - Всё описано в REDME.md

## Как проверить работоспособность:
 - Послез запуска скрипта - перейти по адресу и порту вашей VM

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-11-13 08:10 UTC, mrgreyves requested changes
Здравствуйте!)
У вас где то потерялись тесты
![image](https://github.com/Otus-DevOps-2023-09/GideonRavenor1_infra/assets/34331259/ebbf3477-6c67-4e92-9677-c700182aa8d1)
Постарайтесь вернуть их =)

2023-11-13 08:35 UTC, GideonRavenor1 commented
А я написал к самой задаче в отусе, что я на последнем коммите я обновил README.md, когда уже удалил VM с YC, и что бы мне заново всё не поднимать для прохождения тестов, я пропустил CI, добавив к коммиту skip ci. Если посмотреть предыдущие проверку там все пройдено. Примите пожалуйста так, а то заново всё поднимать и менять в README testapp_IP не очень хочется)

2023-11-13 08:35 UTC, GideonRavenor1 commented
> Здравствуйте!)
> У вас где то потерялись тесты
> ![image](https://github.com/Otus-DevOps-2023-09/GideonRavenor1_infra/assets/34331259/ebbf3477-6c67-4e92-9677-c700182aa8d1)
> Постарайтесь вернуть их =)

Здравствуйте, а я написал к самой задаче в отусе, что я на последнем коммите я обновил README.md, когда уже удалил VM с YC, и что бы мне заново всё не поднимать для прохождения тестов, я пропустил CI, добавив к коммиту skip ci. Если посмотреть предыдущие проверку там все пройдено. Примите пожалуйста так, а то заново всё поднимать и менять в README testapp_IP не очень хочется)

2023-11-16 14:02 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, конечно, все ок =)

2023-11-17 05:57 UTC, merged